/** Catppuccin Mocha color palette. */
export const colors = {
  base: '#1e1e2e',
  mantle: '#181825',
  crust: '#11111b',
  surface0: '#313244',
  surface1: '#45475a',
  surface2: '#585b70',
  overlay0: '#6c7086',
  overlay1: '#7f849c',
  overlay2: '#9399b2',
  subtext0: '#a6adc8',
  subtext1: '#bac2de',
  text: '#cdd6f4',
  lavender: '#b4befe',
  blue: '#89b4fa',
  sapphire: '#74c7ec',
  sky: '#89dceb',
  teal: '#94e2d5',
  green: '#a6e3a1',
  yellow: '#f9e2af',
  peach: '#fab387',
  maroon: '#eba0ac',
  red: '#f38ba8',
  mauve: '#cba6f7',
  pink: '#f5c2e7',
  flamingo: '#f2cdcd',
  rosewater: '#f5e0dc',
};

/** Status colors for common entity states. */
export const statusColors: Record<string, string> = {
  idle: colors.blue,
  active: colors.green,
  working: colors.green,
  waiting: colors.yellow,
  stopped: colors.overlay0,
  error: colors.red,
  pending: colors.yellow,
  assigned: colors.blue,
  in_progress: colors.green,
  completed: colors.teal,
  failed: colors.red,
  canceled: colors.overlay0,
  archived: colors.overlay0,
  cloning: colors.blue,
  cloned: colors.teal,
  running: colors.green,
};
